### ISSUE TITLE
Remaining not working

### ISSUE THREAD

**Issue by asifulmamun** [adityackr/budget-planner#1]

**Comment by adityackr** [comment]
Can you send a screenshot?

**Comment by asifulmamun** [comment]
Yes why not: https://i.postimg.cc/PJ1YGChf/Capture.png

Here the problem is: If you add cost before the budget, then the calculation event is not triger. The calculation trigger only works if you add a new cost.

**Comment by adityackr** [comment]
Ok let me fix it. Thanks for your suggestion.

**Comment by asifulmamun** [comment]
Welcome
